`import DS from 'ember-data'`

Personality = DS.Model.extend
  type:                 DS.attr('string')
  socType:              DS.attr('string')
  quadra:               DS.attr('string')
  club:                 DS.attr('string')
  temperament:          DS.attr('string')
  romanceStyle:         DS.attr('string')
  function1:            DS.attr('string')
  function2:            DS.attr('string')
  function3:            DS.attr('string')
  function4:            DS.attr('string')
  function5:            DS.attr('string')
  function6:            DS.attr('string')
  function7:            DS.attr('string')
  function8:            DS.attr('string')
  description:          DS.attr('string')

Personality.reopenClass
  FIXTURES: [
    { 
      id: 1,
      type: 'entp',
      socType: 'NLE',
      quadra: 'alpha',
      club: 'researchers',
      temperament: 'flexible-maneurvering',
      romanceStyle: 'infantile',
      function1: 'Ne',
      function2: 'Ti',
      function3: 'Se',
      function4: 'Fi',
      function5: 'Si',
      function6: 'Fe',
      function7: 'Ni',
      function8: 'Te',
      description: 'stuff',
    }
    { 
      id: 2,
      type: 'isfp',
      socType: 'SFI',
      quadra: 'alpha',
      club: 'socials',
      temperament: 'receptive-adaptive',
      romanceStyle: 'caregiver',
      function1: 'Si',
      function2: 'Fe',
      function3: 'Ni',
      function4: 'Te',
      function5: 'Ne',
      function6: 'Ti',
      function7: 'Se',
      function8: 'Fi',
      description: 'stuff',
    }
    { 
      id: 3,
      type: 'esfj',
      socType: 'ESE',
      quadra: 'alpha',
      club: 'socials',
      temperament: 'linear-assertive',
      romanceStyle: 'caregiver',
      function1: 'Fe',
      function2: 'Si',
      function3: 'Te',
      function4: 'Ni',
      function5: 'Ti',
      function6: 'Ne',
      function7: 'Fi',
      function8: 'Se',
      description: 'stuff',
    }
    { 
      id: 4,
      type: 'intj',
      socType: 'LII',
      quadra: 'alpha',
      club: 'researchers',
      temperament: 'balanced-stable',
      romanceStyle: 'infantile',
      function1: 'Ti',
      function2: 'Ne',
      function3: 'Fi',
      function4: 'Se',
      function5: 'Fe',
      function6: 'Si',
      function7: 'Te',
      function8: 'Ni',
      description: 'stuff',
    }
    { 
      id: 5,
      type: 'enfj',
      socType: 'EIE',
      quadra: 'beta',
      club: 'humanitarians',
      temperament: 'linear-assertive',
      romanceStyle: 'victim',
      function1: 'Fe',
      function2: 'Ni',
      function3: 'Te',
      function4: 'Si',
      function5: 'Ti',
      function6: 'Se',
      function7: 'Fi',
      function8: 'Ne',
      description: 'stuff',
    }
    { 
      id: 6,
      type: 'istj',
      socType: 'LSI',
      quadra: 'beta',
      club: 'pragmatists',
      temperament: 'balanced-stable',
      romanceStyle: 'aggressor',
      function1: 'Ti',
      function2: 'Se',
      function3: 'Fi',
      function4: 'Ne',
      function5: 'Fe',
      function6: 'Ni',
      function7: 'Te',
      function8: 'Si',
      description: 'stuff',
    }
    { 
      id: 7,
      type: 'estp',
      socType: 'SLE',
      quadra: 'beta',
      club: 'pragmatists',
      temperament: 'flexible-maneurvering',
      romanceStyle: 'aggressor',
      function1: 'Se',
      function2: 'Ti',
      function3: 'Ne',
      function4: 'Fi',
      function5: 'Ni',
      function6: 'Fe',
      function7: 'Si',
      function8: 'Te',
      description: 'stuff',
    }
    { 
      id: 8,
      type: 'infp',
      socType: 'IEI',
      quadra: 'beta',
      club: 'humanitarians',
      temperament: 'receptive-adaptive',
      romanceStyle: 'victim',
      function1: 'Ni',
      function2: 'Fe',
      function3: 'Si',
      function4: 'Te',
      function5: 'Se',
      function6: 'Ti',
      function7: 'Ne',
      function8: 'Fi',
      description: 'stuff',
    }
    { 
      id: 9,
      type: 'esfp',
      socType: 'SEE',
      quadra: 'gamma',
      club: 'socials',
      temperament: 'flexible-maneurvering',
      romanceStyle: 'aggressor',
      function1: 'Se',
      function2: 'Fi',
      function3: 'Ne',
      function4: 'Ti',
      function5: 'Ni',
      function6: 'Te',
      function7: 'Si',
      function8: 'Fe',
      description: 'stuff',
    }
    { 
      id: 10,
      type: 'intp',
      socType: 'ILI',
      quadra: 'gamma',
      club: 'researchers',
      temperament: 'receptive-adaptive',
      romanceStyle: 'victim',
      function1: 'Ni',
      function2: 'Te',
      function3: 'Si',
      function4: 'Fe',
      function5: 'Se',
      function6: 'Fi',
      function7: 'Ne',
      function8: 'Ti',
      description: 'stuff',
    }
    { 
      id: 11,
      type: 'entj',
      socType: 'LIE',
      quadra: 'gamma',
      club: 'researchers',
      temperament: 'linear-assertive',
      romanceStyle: 'victim',
      function1: 'Te',
      function2: 'Ni',
      function3: 'Fe',
      function4: 'Si',
      function5: 'Fi',
      function6: 'Se',
      function7: 'Ti',
      function8: 'Ne',
      description: 'stuff',
    }
    { 
      id: 12,
      type: 'isfj',
      socType: 'ESI',
      quadra: 'gamma',
      club: 'socials',
      temperament: 'balanced-stable',
      romanceStyle: 'aggressor',
      function1: 'Fi',
      function2: 'Se',
      function3: 'Ti',
      function4: 'Ne',
      function5: 'Te',
      function6: 'Ni',
      function7: 'Fe',
      function8: 'Si',
      description: 'stuff',
    }
    { 
      id: 13,
      type: 'estj',
      socType: 'LSE',
      quadra: 'delta',
      club: 'pragmatists',
      temperament: 'linear-assertive',
      romanceStyle: 'caregiver',
      function1: 'Te',
      function2: 'Si',
      function3: 'Fe',
      function4: 'Ni',
      function5: 'Fi',
      function6: 'Ne',
      function7: 'Ti',
      function8: 'Se',
      description: 'stuff',
    }
    { 
      id: 14,
      type: 'infj',
      socType: 'FII',
      quadra: 'delta',
      club: 'humanitarians',
      temperament: 'balanced-stable',
      romanceStyle: 'infantile',
      function1: 'Fi',
      function2: 'Ne',
      function3: 'Ti',
      function4: 'Se',
      function5: 'Te',
      function6: 'Si',
      function7: 'Fe',
      function8: 'Ni',
      description: 'stuff',
    }
    { 
      id: 15,
      type: 'enfp',
      socType: 'NEE',
      quadra: 'delta',
      club: 'humanitarians',
      temperament: 'flexible-maneurvering',
      romanceStyle: 'infantile',
      function1: 'Ne',
      function2: 'Fi',
      function3: 'Se',
      function4: 'Ti',
      function5: 'Si',
      function6: 'Te',
      function7: 'Ni',
      function8: 'Fe',
      description: 'stuff',
    }
    { 
      id: 16,
      type: 'istp',
      socType: 'SLI',
      quadra: 'delta',
      club: 'pragmatists',
      temperament: 'receptive-adaptive',
      romanceStyle: 'caregiver',
      function1: 'Si',
      function2: 'Te',
      function3: 'Ni',
      function4: 'Fe',
      function5: 'Ne',
      function6: 'Fi',
      function7: 'Se',
      function8: 'Ti',
      description: 'stuff',
    }
  ]

`export default Personality`